version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: MinoBankDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - ../../data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  my-volume: