version: '3.3'

services:
  postgresDb:
    container_name: MinoBankDB
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: MinoBankDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - ../../data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgresIdentity:
    container_name: IdentityDB
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: IdentityDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - ../../identityData:/var/lib/postgresql/data
    ports:
      - "5433:5432"
      
volumes:
  data: