// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinoBank.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinoBank.Infrastructure.Migrations
{
    [DbContext(typeof(MinoBankDbContext))]
    [Migration("20250120142735_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinoBank.Core.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankAccountDetails", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BankAccountId");

                    b.ToTable("BankAccountDetails");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DailyLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankCardDetails", b =>
                {
                    b.Property<Guid>("BankCardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("integer");

                    b.Property<string>("CvvCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BankCardId");

                    b.ToTable("BankCardDetails");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientBankCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SenderBankCardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipientBankCardId");

                    b.HasIndex("SenderBankCardId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankAccountDetails", b =>
                {
                    b.HasOne("MinoBank.Core.Entities.BankAccount", "BankAccount")
                        .WithOne("Details")
                        .HasForeignKey("MinoBank.Core.Entities.BankAccountDetails", "BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankCard", b =>
                {
                    b.HasOne("MinoBank.Core.Entities.BankAccount", "BankAccount")
                        .WithMany("BankCards")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankCardDetails", b =>
                {
                    b.HasOne("MinoBank.Core.Entities.BankCard", "BankCard")
                        .WithOne("Details")
                        .HasForeignKey("MinoBank.Core.Entities.BankCardDetails", "BankCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankCard");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankTransaction", b =>
                {
                    b.HasOne("MinoBank.Core.Entities.BankCard", "RecipientBankCard")
                        .WithMany("RecivedTransactions")
                        .HasForeignKey("RecipientBankCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinoBank.Core.Entities.BankCard", "SenderBankCard")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderBankCardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RecipientBankCard");

                    b.Navigation("SenderBankCard");
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankAccount", b =>
                {
                    b.Navigation("BankCards");

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("MinoBank.Core.Entities.BankCard", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("RecivedTransactions");

                    b.Navigation("SentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
